import type { DeterministicMappingSpec } from "./engine";

export const openAiPricingMappingV1: DeterministicMappingSpec = {
  mappingId: "map_openai_pricing_v1",
  revision: 1,
  status: "active",
  sourceSchema: "ai-infrastructure.source.v1",
  sourceType: "pricing",
  canonicalSchema: "ai_infrastructure",
  canonicalSchemaRevision: 1,
  entityType: "model",
  sourceKey: "provider_model_id",
  canonicalKey: ["model.provider_id", "model.provider_model_id"],
  fields: [
    {
      target: "model.provider_id",
      source: "$observation.provider.id",
      transforms: [{ name: "normalize_identifier" }],
      required: true,
      evidencePaths: ["$observation.provider.id"],
    },
    {
      target: "model.provider_model_id",
      source: "provider_model_id",
      transforms: [{ name: "normalize_identifier" }],
      required: true,
      evidencePaths: ["provider_model_id"],
    },
    {
      target: "model.display_name",
      source: "display_name",
      transforms: [{ name: "normalize_whitespace" }],
      required: true,
      evidencePaths: ["display_name"],
    },
    {
      target: "model.pricing_plan",
      source: "plan",
      transforms: [{ name: "normalize_identifier" }],
      required: true,
      evidencePaths: ["plan"],
    },
    {
      target: "model.input_price_usd_per_million_tokens",
      source: "input_price.amount",
      transforms: [{ name: "rename" }],
      required: true,
      evidencePaths: ["input_price.currency", "input_price.denominator", "input_price.original"],
    },
    {
      target: "model.output_price_usd_per_million_tokens",
      source: "output_price.amount",
      transforms: [{ name: "rename" }],
      required: true,
      evidencePaths: ["output_price.currency", "output_price.denominator", "output_price.original"],
    },
  ],
};

export const openAiCatalogMappingV1: DeterministicMappingSpec = {
  mappingId: "map_openai_catalog_v1",
  revision: 1,
  status: "active",
  sourceSchema: "ai-infrastructure.source.v1",
  sourceType: "catalog",
  canonicalSchema: "ai_infrastructure",
  canonicalSchemaRevision: 1,
  entityType: "model",
  sourceKey: "provider_model_id",
  canonicalKey: ["model.provider_id", "model.provider_model_id"],
  fields: [
    {
      target: "model.provider_id",
      source: "$observation.provider.id",
      transforms: [{ name: "normalize_identifier" }],
      required: true,
      evidencePaths: ["$observation.provider.id"],
    },
    {
      target: "model.provider_model_id",
      source: "provider_model_id",
      transforms: [{ name: "normalize_identifier" }],
      required: true,
      evidencePaths: ["provider_model_id"],
    },
    {
      target: "model.display_name",
      source: "display_name",
      transforms: [{ name: "normalize_whitespace" }],
      required: true,
      evidencePaths: ["display_name"],
    },
    {
      target: "model.family",
      source: "family",
      transforms: [{ name: "normalize_identifier" }],
      required: true,
      evidencePaths: ["family"],
    },
    {
      target: "model.status",
      source: "lifecycle_status",
      transforms: [{ name: "normalize_case", mode: "lower" }],
      required: true,
      evidencePaths: ["lifecycle_status"],
    },
    {
      target: "model.context_window_tokens",
      source: "context_window_tokens",
      transforms: [{ name: "default", value: null }],
      required: false,
      evidencePaths: ["context_window_tokens"],
    },
    {
      target: "model.max_output_tokens",
      source: "max_output_tokens",
      transforms: [{ name: "default", value: null }],
      required: false,
      evidencePaths: ["max_output_tokens"],
    },
    {
      target: "model.supports_tools",
      source: "capabilities.tools",
      transforms: [{ name: "normalize_boolean" }],
      required: true,
      evidencePaths: ["capabilities.tools"],
    },
    {
      target: "model.supports_structured_output",
      source: "capabilities.structured_output",
      transforms: [{ name: "normalize_boolean" }],
      required: true,
      evidencePaths: ["capabilities.structured_output"],
    },
  ],
};
