import type { CanonicalSchemaRevision } from "./compatibility";

export const aiInfrastructureCanonicalSchemaV1: CanonicalSchemaRevision = {
  schemaId: "ai_infrastructure",
  domain: "ai-infrastructure",
  revision: 1,
  status: "active",
  fields: [
    {
      path: "model.provider_id",
      entityType: "model",
      dataType: "string",
      meaning: "Stable provider identifier that owns the model namespace.",
      unit: "identifier",
      required: true,
      nullable: false,
      evidenceMinimumSupport: 1,
      severity: "critical",
    },
    {
      path: "model.provider_model_id",
      entityType: "model",
      dataType: "string",
      meaning: "Provider-controlled model identifier.",
      unit: "identifier",
      required: true,
      nullable: false,
      evidenceMinimumSupport: 1,
      severity: "critical",
    },
    {
      path: "model.display_name",
      entityType: "model",
      dataType: "string",
      meaning: "Human-readable provider model name.",
      unit: "text",
      required: true,
      nullable: false,
      evidenceMinimumSupport: 1,
      severity: "material",
    },
    {
      path: "model.status",
      entityType: "model",
      dataType: "enum",
      meaning: "Current provider lifecycle classification.",
      unit: "status",
      required: false,
      nullable: true,
      enumValues: ["preview", "active", "deprecated", "retired", "unknown"],
      evidenceMinimumSupport: 1,
      severity: "critical",
    },
    {
      path: "model.context_window_tokens",
      entityType: "model",
      dataType: "integer",
      meaning: "Maximum documented context window in tokens.",
      unit: "tokens",
      required: false,
      nullable: true,
      minimum: 1,
      maximum: 100_000_000,
      evidenceMinimumSupport: 1,
      severity: "material",
    },
    {
      path: "model.input_price_usd_per_million_tokens",
      entityType: "pricing_plan",
      dataType: "number",
      meaning: "Standard input token price in USD per million tokens.",
      unit: "usd_per_million_input_tokens",
      required: false,
      nullable: true,
      minimum: 0,
      evidenceMinimumSupport: 1,
      severity: "critical",
    },
    {
      path: "model.output_price_usd_per_million_tokens",
      entityType: "pricing_plan",
      dataType: "number",
      meaning: "Standard output token price in USD per million tokens.",
      unit: "usd_per_million_output_tokens",
      required: false,
      nullable: true,
      minimum: 0,
      evidenceMinimumSupport: 1,
      severity: "critical",
    },
  ],
};

export const aiInfrastructureCanonicalSchemaV2Draft: CanonicalSchemaRevision = {
  ...aiInfrastructureCanonicalSchemaV1,
  revision: 2,
  status: "draft",
  fields: [
    ...aiInfrastructureCanonicalSchemaV1.fields,
    {
      path: "model.region",
      entityType: "region",
      dataType: "string",
      meaning: "Optional provider-defined region scope for the observation.",
      unit: "provider_region",
      required: false,
      nullable: true,
      evidenceMinimumSupport: 1,
      severity: "informational",
    },
  ],
};
